import { SceneComponent } from "./types";

export const DEMO_SCENE: SceneComponent[] = [
  {
    id: "U1",
    type: "ic",
    value: "TPS563201",
    position: [0, 0, 0],
    reasoning: "Synchronous buck converter IC, SOT-23-6 package",
    partNumber: "TPS563201DDCR",
    price: "$0.62",
    url: "https://www.digikey.com/en/products/detail/texas-instruments/TPS563201DDCR/5012183",
    inStock: true,
    distributor: "Digikey",
    package: "SOT-23-6",
  },
  {
    id: "R1",
    type: "resistor",
    value: "100kΩ",
    position: [-3.5, 0, 1.2],
    reasoning: "Upper feedback divider — sets Vout reference voltage",
    partNumber: "RC0402FR-07100KL",
    price: "$0.10",
    url: "https://www.digikey.com/en/products/detail/yageo/RC0402FR-07100KL/726764",
    inStock: true,
    distributor: "Digikey",
    package: "0402",
  },
  {
    id: "R2",
    type: "resistor",
    value: "22.1kΩ",
    position: [-3.5, 0, -1.2],
    reasoning: "Lower feedback divider — Vout = 0.765V × (1 + R1/R2) = 5V",
    partNumber: "RC0402FR-0722K1L",
    price: "$0.10",
    url: "https://www.digikey.com/en/products/detail/yageo/RC0402FR-0722K1L/728024",
    inStock: true,
    distributor: "Digikey",
    package: "0402",
  },
  {
    id: "L1",
    type: "inductor",
    value: "4.7µH",
    position: [2.8, 0, 0],
    reasoning: "Output inductor — L = (Vin−Vout) / (ΔIL × fsw) at 500kHz, >2.5A rating",
    partNumber: "SRR1260-4R7Y",
    price: "$0.68",
    url: "https://www.digikey.com/en/products/detail/bourns-inc/SRR1260-4R7Y/2756070",
    inStock: true,
    distributor: "Digikey",
    package: "1260",
  },
  {
    id: "Cin",
    type: "capacitor_ceramic",
    value: "10µF 25V",
    position: [-2.2, 0, -3],
    reasoning: "Input decoupling — reduces switching noise on Vin rail",
    partNumber: "C1210C106K3RACTU",
    price: "$0.28",
    url: "https://www.digikey.com/en/products/detail/kemet/C1210C106K3RACTU/3988084",
    inStock: true,
    distributor: "Digikey",
    package: "1210",
  },
  {
    id: "Cout",
    type: "capacitor_ceramic",
    value: "47µF 10V",
    position: [2.5, 0, -3],
    reasoning: "Output filter — Cout = ΔIL / (8 × fsw × ΔVout), low ESR ceramic",
    partNumber: "GRM32ER61A476ME20L",
    price: "$0.43",
    url: "https://www.digikey.com/en/products/detail/murata-electronics/GRM32ER61A476ME20L/4936771",
    inStock: true,
    distributor: "Digikey",
    package: "1210",
  },
  {
    id: "Cboot",
    type: "capacitor_ceramic",
    value: "100nF",
    position: [0.8, 0, 2.5],
    reasoning: "Bootstrap cap — charges high-side gate drive supply between switches",
    partNumber: "GRM155R71C104KA88D",
    price: "$0.10",
    url: "https://www.digikey.com/en/products/detail/murata-electronics/GRM155R71C104KA88D/490-1532",
    inStock: true,
    distributor: "Digikey",
    package: "0402",
  },
];

// Manhattan trace connections: [fromId, toId]
export const DEMO_TRACES: [string, string][] = [
  ["U1", "L1"],
  ["L1", "Cout"],
  ["U1", "R1"],
  ["R1", "R2"],
  ["U1", "Cboot"],
  ["Cin", "U1"],
  ["R2", "Cout"],
];

export const DEMO_ASSEMBLY = [
  { stepNumber: 1, instruction: "Place and solder U1 (TPS563201) — align pin 1 marker, reflow all 6 pads.", componentId: "U1" },
  { stepNumber: 2, instruction: "Solder Cin (10µF input cap) close to the VIN pin to minimise input impedance.", componentId: "Cin" },
  { stepNumber: 3, instruction: "Solder Cboot (100nF bootstrap cap) between BOOT and SW pins.", componentId: "Cboot" },
  { stepNumber: 4, instruction: "Solder L1 (4.7µH inductor) on the switch node — keep trace to SW pin short.", componentId: "L1" },
  { stepNumber: 5, instruction: "Solder Cout (47µF output cap) at the inductor output node.", componentId: "Cout" },
  { stepNumber: 6, instruction: "Solder R1 (100kΩ) — upper feedback resistor from Vout to FB pin.", componentId: "R1" },
  { stepNumber: 7, instruction: "Solder R2 (22.1kΩ) — lower feedback resistor from FB pin to GND. Verify Vout = 5V.", componentId: "R2" },
];
